# Generated by Django 5.0.4 on 2024-09-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('bank_name', models.CharField(max_length=20)),
                ('program', models.CharField(max_length=30)),
                ('betting', models.CharField(max_length=10)),
                ('perviy_vznos', models.CharField(max_length=10)),
                ('year_deadline', models.CharField(max_length=10)),
                ('monthly_cost', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Program_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('full_name', models.CharField(max_length=30)),
                ('text', models.TextField()),
            ],
        ),
    ]
