# Generated by Django 5.0.4 on 2024-10-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_about_is_active_discounts_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='finished_at',
            field=models.DateTimeField(),
        ),
    ]
